### ISSUE TITLE
UnicodeEncodeError at Start

### ISSUE THREAD

**Issue by bastelwastel** [neandr/piScheduler#2]
Hello, 
I have a Problem at the startup from piSchedule.
After installation and starting with python piSchedule.py -ini the script quit with :

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 4: ordinal not in range(128)

I am using a Pi2 with 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l GNU/Linux

Do you have an idea what this could be ?

Greetings an Thank You

Bastelwastel

**Comment by framps** [comment]
Could you please post the whole stacktrace you get including the linenumber the code the error occurs?

**Comment by bastelwastel** [comment]
Hello framps,

In the meantime, some for me , strange things happened. As i startup piSchedule Sunday evening to copy the Output of the program, it works. I could choose a ini File and piSchedule was reachabele via webbrowser. ?! But no Job did work, no switching despite piSchedule shows that the Job was done. I dont know why and How, checking my config.json from pilight shows me an "empty" default config. After replacing it with my backup-config.json Monday evening piSchedule switsched my wireles socket.... Really strange...

**Comment by neandr** [comment]
@bastelwastel 
Sorry to come to this only today. 
Did send a stacktrace to framp?
The only reason for a problem after startup with an encode error, I could imagine the file name contains non-ascii characters.

Also with your second posting I don't understand what happens. We have installed and running piSchedule on pilight v6 without problems. Be sure pilight is running before you start piSchedule!

Did you tried to install pilight/piSchedule on a fresh raspberry installation.

Guenter

**Comment by neandr** [comment]
@bastelwastel 
Any news about this?
Would like to close this issue.
Günter

**Comment by neandr** [comment]
Just checked with non-ascii naming of INI files. That will produce an error and terminates piSchedule.
Please use *only* ascii characters with INI file naming.

**Comment by bastelwastel** [comment]
Hallo Günther, 

at the Moment we are on holiday. We will back next week. I leave a reply then

Greetings 

Bastelwastel


Am 8. Juni 2015 11:41:09 MESZ, schrieb Guenter <notifications@github.com>:
>@bastelwastel 
>Any news about this?
>Would like to close this issue.
>Günter
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/neandr/piScheduler/issues/2#issuecomment-109931372

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by bastelwastel** [comment]
@neandr 

Hello Günther,

sorry for my late reply but we`ve had problems with our Internet Connection.
About 14 Days without an working DSL was am mess.

Pischedule worked during our holidays well, no Problems. 

The error appeared before I could choose such an INI File,
and I did not create an own INI File before starting Pischedule.
