### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by CoderXY** [neandr/piScheduler#3]
Hey there,

i installed piScheduler on my Raspberry with pilight v 7.0. Because this piScheduler Version is not compatible with the newest pilight.That´s why I improved the sourcecode:

1. piDiscover.py is not able to get the port from the config.json in line 61 because of new json tag names.

2. in install_piScheduler.sh the last line should be: "python piSchedule.py -ini" instead of "python pySchedule.py -ini"
3. piSchedule.py line 393:
jobs.append(sched.add_job(fire_pilight, 'date', run_date=str(xTime), args=[{'message':message, 'info':info}], name=jobName))
should be changed to:
trigger = DateTrigger( run_date=str(xTime))
jobs.append(sched.add_job(fire_pilight, 'date',trigger,  args=[{'message':message, 'info':info}], name=jobName))

Hope that helped.

By the way, why does the webGui is loading very long with a smartphone but not with a desktop pc?

CODERXY

**Comment by neandr** [comment]
Thanks for the feedback.

Some notes:  first webGUI loading I feel is the same here, sometimes I have problems to connect to the RPI at all via WLAN. There was a method posted on pulight forum which said to solve the situation ... never tested it.
Currently I'm working on some improvments which will be compatible with pilight 7.
ad 2. typo, yes .. will fix that
ad 3. have to check
